### PR TITLE
Refactor and modularize

### PR DESCRIPTION
**Pull request by kofferdahl**
A first pass at making image_processor_gui more modular, related to #89. 

I think everything is still working, but I request that @mjp59 and @matthew-huber do you best to break it (ignoring any existing bugs) before we merge this.

### CODE REVIEW

**Comment by mjp59** [comment]
@kofferdahl I got it to break if I selected a normal file type and a zip file at the same time. 

File "image_processor_gui.py", line 304, in file_select_button
    self.openFileNamesDialog()
  File "image_processor_gui.py", line 355, in openFileNamesDialog
    fn = validateFiles(fn)
  File "image_processor_gui.py", line 587, in validateFiles
    file = file_list[inx]
IndexError: list index out of range

got this error

**Comment by kofferdahl** [comment]
@mjp59 Given how we restrict how users select files, how are you able to select a zip file and another file type simultaneously?

**Comment by kofferdahl** [comment]
@mjp59 that's interesting - window's won't let me do that (files that don't have the right extension don't even show up). Do you know if that works on the current master branch?  I just pushed something that I think should fix it. Lmk if it works or not (sorry I can't test it myself).

**Comment by mjp59** [comment]
@kofferdahl that fixed it! Nice!

**Comment by mjp59** [comment]
@kofferdahl @matthew-huber broke it again by clicking zip files when downloading multiple images. 

 File "image_processor_gui.py", line 251, in download_all_images
    filename, processing_type = self.download_image()
  File "image_processor_gui.py", line 239, in download_image
    processing_type = processing_type["process_done"]
KeyError: 'process_done'

This was the error message

**Comment by mjp59** [comment]
@kofferdahl @matthew-huber the zip file was created correctly but the gui crashed weird stuff

**Comment by kofferdahl** [comment]
@mjp59  Okay I think I got it. It's weird that it only happened with downloading uploaded zip files, considering it was an issue with how images were uploaded/stored in the database. But it should be working now.

**Comment by matthew-huber** [comment]
Checked it and it works for everything I could do previously

**Comment by kofferdahl** [comment]
@mjp59 Do I have your approval to merge too?

**Pull request merged**
